In [1]:
import open3d as o3d
import time
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
x = np.linspace(-3, 3, 401)
mesh_x, mesh_y = np.meshgrid(x, x)
z = np.sinc((np.power(mesh_x, 2) + np.power(mesh_y, 2)))
z_norm = (z - z.min()) / (z.max() - z.min())
xyz = np.zeros((np.size(mesh_x), 3))
xyz[:, 0] = np.reshape(mesh_x, -1)
xyz[:, 1] = np.reshape(mesh_y, -1)
xyz[:, 2] = np.reshape(z_norm, -1)
print('xyz')
print(xyz)

# Pass xyz to Open3D.o3d.geometry.PointCloud and visualize
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(xyz)
o3d.io.write_point_cloud("./sync.ply", pcd)

# Load saved point cloud and visualize it
pcd_load = o3d.io.read_point_cloud("./sync.ply")
o3d.visualization.draw_geometries([pcd_load])

# convert Open3D.o3d.geometry.PointCloud to numpy array
xyz_load = np.asarray(pcd_load.points)
print('xyz_load')
print(xyz_load)

# save z_norm as an image (change [0,1] range to [0,255] range with uint8 type)
img = o3d.geometry.Image((z_norm * 255).astype(np.uint8))
o3d.io.write_image("./sync.png", img)
o3d.visualization.draw_geometries([img])

xyz
[[-3.         -3.          0.17846472]
 [-2.985      -3.          0.17440115]
 [-2.97       -3.          0.17063709]
 ...
 [ 2.97        3.          0.17063709]
 [ 2.985       3.          0.17440115]
 [ 3.          3.          0.17846472]]
xyz_load
[[-3.         -3.          0.17846472]
 [-2.985      -3.          0.17440115]
 [-2.97       -3.          0.17063709]
 ...
 [ 2.97        3.          0.17063709]
 [ 2.985       3.          0.17440115]
 [ 3.          3.          0.17846472]]


In [2]:
vis = o3d.visualization.Visualizer()
vis.create_window()

# geometry is the point cloud used in your animaiton
geometry = o3d.geometry.PointCloud()
geometry.points = o3d.utility.Vector3dVector(np.random.randn(1000, 3))
vis.add_geometry(geometry)
# vis.add_geometry(geometry)
# print("draw")

# for i in range(10):
    # now modify the points of your geometry
    # you can use whatever method suits you best, this is just an examp


# vis.update_geometry(geometry)
vis.poll_events()
vis.update_renderer()
    # time.sleep(1.0)
    


In [3]:
import open3d as o3d
import numpy as np

def create_transform_matrix_from_z(z):
    """ Return transform 4x4 transformation matrix given a Z value """
    result = np.identity(4)
    result[2,3] = z # Change the z
    
    return result

# Create Open3d visualization window
vis = o3d.visualization.Visualizer()
vis.create_window()

# create sphere geometry
sphere1 = o3d.geometry.TriangleMesh.create_sphere()
vis.add_geometry(sphere1)

# create coordinate frame
coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame()
vis.add_geometry(coordinate_frame)

prev_tf = None
for curr_z in np.arange(0.5, 15.0, 0.005):
    # return sphere1 to original position (0,0,0)
    if prev_tf is not None:
        sphere1.transform(np.linalg.inv(prev_tf))

    # transform bazed on curr_z tf
    curr_tf = create_transform_matrix_from_z(curr_z)
    sphere1.transform(curr_tf)

    prev_tf = curr_tf

    vis.update_geometry(sphere1)
    vis.poll_events()
    vis.update_renderer()

KeyboardInterrupt: 

: 